version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=your_secret_key
    command: uvicorn hw13_fastapi_app:app --host 0.0.0.0 --port 8000
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
